spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop
    show-sql: true
    properties:
        hibernate:
            format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: test_user
    password: test_password
    driver-class-name: org.postgresql.Driver
server:
    port: 3000
    servlet:
      context-path: /api